version: "3.8"
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      HOST: ${DB_HOST}

